version: '3.9'

services:
  web:
    image: php:8.2-apache
    volumes:
      - ./project:/var/www/html/
    #user: web:web
    ports:
      - 80:80
    environment:
      #PHP_IDE_CONFIG: 'serverName=web.local'
      #APACHE_SERVER_NAME: web.local
      APPLICATION_ENV: development
      APACHE_LOG_DIR: /var/log/apache2
      APACHE_DOCUMENT_ROOT: /var/www/html
      #APACHE_RUN_USER: web
      #APACHE_RUN_GROUP: web
    networks:
      - development

  db:
    image: mysql:8.0.37-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apache_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    networks:
      - development

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 81:80
    environment:
      PMA_HOST: db
      PMA_USER: devuser
      PMA_PASSWORD: devpass
      UPLOAD_LIMIT: 2048
    networks:
      - development

networks:
  development: