services:
  friends:
    build:
      context: ./friends/php/
      dockerfile: Dockerfile
    environment:
      - PORT=80
    deploy:
      replicas: 5
    networks:
      - loadbalancing
  friends-load-balancer:
    build:
      context: ./friends/nginx/
      dockerfile: Dockerfile
    container_name: load_balancer_friends
    ports:
      - "81:80"
    networks:
      - loadbalancing
    depends_on:
      - friends
    friends-db:
      image: mysql
      command: --mysql-native-password=ON
      restart: always
      ports:
        - 3307:3306
      volumes:
        - ./db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: friends
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass

  messages:
    build:
      context: ./messages/php/
      dockerfile: Dockerfile
    environment:
      - PORT=80
    deploy:
      replicas: 5
    networks:
      - loadbalancing
  messages-load-balancer:
    build:
      context: ./messages/nginx/
      dockerfile: Dockerfile
    container_name: load_balancer_messages
    ports:
      - "82:80"
    networks:
      - loadbalancing
    depends_on:
      - messages
    messages-db:
      image: mysql
      command: --mysql-native-password=ON
      restart: always
      ports:
        - 3308:3306
      volumes:
        - ./db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: messages
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass

  posts:
    build:
      context: ./posts/php/
      dockerfile: Dockerfile
    environment:
      - PORT=80
    deploy:
      replicas: 5
    networks:
      - loadbalancing
  posts-load-balancer:
    build:
      context: ./posts/nginx/
      dockerfile: Dockerfile
    container_name: load_balancer_posts
    ports:
      - "83:80"
    networks:
      - loadbalancing
    depends_on:
      - posts
    posts-db:
      image: mysql
      command: --mysql-native-password=ON
      restart: always
      ports:
        - 3309:3306
      volumes:
        - ./db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: posts
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass

  users:
    build:
      context: ./users/php/
      dockerfile: Dockerfile
    environment:
      - PORT=80
    deploy:
      replicas: 5
    networks:
      - loadbalancing
  users-load-balancer:
    build:
      context: ./users/nginx/
      dockerfile: Dockerfile
    container_name: load_balancer_users
    ports:
      - "84:80"
    networks:
      - loadbalancing
    depends_on:
      - users
    users-db:
      image: mysql
      command: --mysql-native-password=ON
      restart: always
      ports:
        - 3310:3306
      volumes:
        - ./db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: users
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass

  profiles:
    build:
      context: ./profiles/php/
      dockerfile: Dockerfile
    environment:
      - PORT=80
    deploy:
      replicas: 5
    networks:
      - loadbalancing
  profiles-load-balancer:
    build:
      context: ./profiles/nginx/
      dockerfile: Dockerfile
    container_name: load_balancer_profiles
    ports:
      - "85:80"
    networks:
      - loadbalancing
    depends_on:
      - profiles
    profiles-db:
      image: mysql
      command: --mysql-native-password=ON
      restart: always
      ports:
        - 3311:3306
      volumes:
        - ./db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: profiles
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass

networks:
  loadbalancing:
